parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

env:
  browser: true
  es6: true
  jest: true

extends:
  - airbnb
  - prettier
  - prettier/react

plugins:
  - prettier

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx

      moduleDirectory:
        - node_modules
        - src

rules:
  prettier/prettier:
    - error
    - printWidth: 80
      tabWidth: 2
      useTabs: false
      semi: true
      singleQuote: true
      trailingComma: all
      bracketSpacing: false
      jsxBracketSameLine: false
      arrowParens: avoid

  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - src/stories/*.{js,jsx}

  no-underscore-dangle: off

  jsx-a11y/anchor-is-valid:
    - error
    - components:
      - Link
      specialLink:
      - to
